package constants

const (
	CTX_ID_PARAM      = "id"
	CTX_KEY_ROLE_NAME = "role"

	ENUM_ROLE_ADMIN = "admin"
	ENUM_ROLE_USER  = "user"

	ENUM_RUN_PRODUCTION = "production"
	ENUM_RUN_TESTING    = "testing"

	ENUM_PAGINATION_LIMIT = 10
	ENUM_PAGINATION_PAGE  = 1

	// PAYMENT METHOD
	ENUM_TRIPAY_PAYMENT_METHOD_QRIS = "QRIS"
)
